### PR TITLE
Added a useful link

### PR DESCRIPTION
**Pull request by Vaishnaviamirayada**
Have added a useful link about debugging a program from scaler topics in the reference section.

### Types of changes

- [ ] Docs change / refactoring / dependency upgrade
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by fennecdjay — COMMENTED** [review]
lgtm, the link is working and points to a resource that seems useful

**Comment by fennecdjay** [comment]
I would wait for @mertyildiran 's advice before merging tho.
Thanks for the contribution

**Comment by mertyildiran** [comment]
Closing because it's a spam.

**Comment by Vaishnaviamirayada** [comment]
Hi @mertyildiran,

I am not sure why you said it's a spam, The resource I have added is useful to the user.

[Debugging a C Program](https://www.scaler.com/topics/c/debugging-c-program/) explained in-depth in the article which I believe will help the reader who is looking for information about it.

If you still feel it's a Spam keep it closed.

Thank you!

**Pull request closed without merging**
